In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
import math as m
import random
import copy

In [2]:
#Translation     利用平移矩阵和cv2.warpAffine函数进行平移操作
'''
viod cv2::warpAffine(
        inputArray   image
        outputArray  dst
        intputArray  Matrix
        Size         (col, row)
        int flags =  INTER_LINEAR                  #插值Mode
        int borderMode = BORDER_CONSTANT           #边界像素Mode
)

'''
img = cv2.imread('cat1.jpg')
cv2.imshow('input image', img)

row, col, ch = img.shape
print (img.shape)
M = np.float32([[1,0,50], [0,1,50]])    #注意这里一定要是np.float32 不能是np.array
dst = cv2.warpAffine(img, M, (col, row))

cv2.imshow('output image', dst)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

(124, 143, 3)


In [7]:
M = cv2.getRotationMatrix2D((0,0),30, 1)
print(M)


[[ 0.8660254  0.5        0.       ]
 [-0.5        0.8660254  0.       ]]


In [6]:
#Rotation
'''
通过生成的旋转矩阵和库函数进行旋转操作
'''
img = cv2.imread('cat1.jpg')
cv2.imshow('input image', img)
#M = cv2.getRotationMatrix2D((col/2, row/2), 30, 1)
M = np.float32([[0.866, 0.5, img.shape[0]/2], [-0.5, 0.866, img.shape[1]/2]])
print(M)
#dst = cv2.warpAffine(img, M, (col*2, row*2))
dst = cv2.warpAffine(img, M, (col, row))

cv2.imshow('output image', dst)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

[[ 0.866  0.5   62.   ]
 [-0.5    0.866 71.5  ]]


In [14]:
#图像映射  
'''
需要选出原图中的3个坐标点和对应的映射点，整幅图片将根据上述映射关系变换
'''
img = cv2.imread('cat1.jpg')
cv2.imshow('input image', img)

pts1 = np.float32([[20,20],[100,95], [50, 30]])       #映射前原图上找出三个点
pts2 = np.float32([[20,40],[100,90], [100, 5]])       #上述3个点对应映射后的位置

M = cv2.getAffineTransform(pts1, pts2)
dst = cv2.warpAffine(img, M, (col, row), cv2.INTER_LINEAR)

cv2.imshow('output image', dst)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [49]:
#投影/透视变换
#cv2.warpPerspective()
src = cv2.imread('111.png')
print (src.shape)
src_points = np.array([[165., 270.], [835., 270.], [360., 125.], [615., 125.]], dtype = "float32")
dst_points = np.array([[165., 270.], [835., 270.], [165., 30.], [835., 30.]], dtype = "float32")

M = cv2.getPerspectiveTransform(src_points, dst_points)
perspective = cv2.warpPerspective(src, M, (960, 270), cv2.INTER_LINEAR);
        
cv2.imshow('out',perspective)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

(271, 960, 3)


In [42]:
print(img[-50,50])

[227 237 237]


In [22]:
#自己选择4个点进行投射变换
import cv2
import numpy as np

img = cv2.imread("chumoping.png")
#print img.shape
set_point = []

i = 1
def on_EVENT_LBUTTONDOWN(event, x, y, flags, param):
    if event == cv2.EVENT_LBUTTONDOWN:
        xy = "%d,%d" % (x, y)
        print (xy)
        temp = [x,y]
        set_point.append(temp)
        '''此处在图像上点击8个点，每四个作为一组'''
        cv2.circle(img, (x, y), 1, (255, 0, 0), thickness = -1)
        cv2.putText(img, xy, (x, y), cv2.FONT_HERSHEY_PLAIN,
                    1.0, (0,0,0), thickness = 1)
        cv2.imshow("image", img)



cv2.namedWindow("image")
cv2.setMouseCallback("image", on_EVENT_LBUTTONDOWN)
cv2.imshow("image", img)



key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()


249,367
29,561
1099,575
879,372
51,43
34,560
1106,575
1089,34


In [24]:
#print (len(set_point))8
source = set_point[0:4]
target = set_point[4:8]

src = cv2.imread("chumoping.png")
cv2.imshow('input', src)
row, col, ch = src.shape
src_points = np.array(source, dtype = "float32")
dst_points = np.array(target, dtype = "float32")
M = cv2.getPerspectiveTransform(src_points, dst_points)

dst = cv2.warpPerspective(src, M, (col, row), cv2.INTER_LINEAR)

cv2.imshow('out',dst)
key = cv2.waitKey()
if key == 27:
    cv2.destroyAllWindows()

In [57]:
for i in range(2):
    cv2.setMouseCallback("image", on_EVENT_LBUTTONDOWN)
    print('asdasdasd')

asdasdasd
asdasdasd


In [21]:
def random_warp(img, row, col):
    height, width, channels = img.shape

    # warp:
    random_margin = 60
    x1 = random.randint(-random_margin, random_margin)
    y1 = random.randint(-random_margin, random_margin)
    x2 = random.randint(width - random_margin - 1, width - 1)
    y2 = random.randint(-random_margin, random_margin)
    x3 = random.randint(width - random_margin - 1, width - 1)
    y3 = random.randint(height - random_margin - 1, height - 1)
    x4 = random.randint(-random_margin, random_margin)
    y4 = random.randint(height - random_margin - 1, height - 1)

    dx1 = random.randint(-random_margin, random_margin)
    dy1 = random.randint(-random_margin, random_margin)
    dx2 = random.randint(width - random_margin - 1, width - 1)
    dy2 = random.randint(-random_margin, random_margin)
    dx3 = random.randint(width - random_margin - 1, width - 1)
    dy3 = random.randint(height - random_margin - 1, height - 1)
    dx4 = random.randint(-random_margin, random_margin)
    dy4 = random.randint(height - random_margin - 1, height - 1)

    pts1 = np.float32([[x1, y1], [x2, y2], [x3, y3], [x4, y4]])
    pts2 = np.float32([[dx1, dy1], [dx2, dy2], [dx3, dy3], [dx4, dy4]])
    print(pts1)
    print(pts2)
    M_warp = cv2.getPerspectiveTransform(pts1, pts2)
    img_warp = cv2.warpPerspective(img, M_warp, (width, height))
    return M_warp, img_warp
M_warp, img_warp = random_warp(img, img.shape[0], img.shape[1])
cv2.imshow('output', img_warp)
key = cv2.waitKey(0)
if key == 27:
    cv2.destroyAllWindows()

[[-42.  24.]
 [ 86.  57.]
 [132.  63.]
 [ 19. 121.]]
[[ 45. -45.]
 [112.  46.]
 [ 96.  69.]
 [-58. 115.]]


In [5]:
#镜像

img = cv2.imread('shiguanzhang.png')
cv2.imshow('input', img)

size = img.shape
#print(size)   (430, 764, 3)

iLR = copy.deepcopy(img)           #获得一个和原始图像相同的图像，注意这里要使用深度复制
h = size[0]
w = size[1]

for row in range(h):
    for col in range(w):
        iLR[h-row-1, w-col-1] = img[row, col]

cv2.imshow('output', iLR)
key = cv2.waitKey(0)
if key == 27:
    cv2.destroyAllWindows()